import Quiz from "@/app/quiz/quiz"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "No Drugs pls | Quiz",
  description: "Generated by create next app",
};
export default function Main() {
  return (
    <div className="bg-gradient-to-bl from-teal-200 to-slate-200 dark:from-slate-950 dark:to-emerald-950 pt-20">
      <div>
        
        <Quiz />
      </div>
    </div>
  )
}