import Quiz from "@/app/quiz/quiz"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "No Drugs pls | Quiz",
  description: "Generated by create next app",
};
export default function Main() {
    return (
        <Quiz />
    )
}