import Signi from "@/app/sign-in/[[...sign-in]]/signi"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "No Drugs pls | Sign In",
  description: "Generated by create next app",
};
export default function Main() {
    return (
        <Signi />
    )
}