import Signu from "@/app/sign-up/[[...sign-up]]/signu"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "No Drugs pls | Sign Up",
  description: "Generated by create next app",
};
export default function Main() {
  return (
    <div>
      <div className="pt-20" />
      <Signu />
    </div>
  )
}